import '../src/style/globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Navbar from "@/src/components/header";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Assignment',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Navbar/>
        <main className={'font-sans'}>{children}</main>
        </body>
        </html>
    )
}
